#!/usr/bin/env bash
# This is a Bash script that displays "Best School" 10 times.
# Counter variable
count=0
# While loop to display "Best School" 10 times
while [ $count -lt 10 ]; do
    echo "Best School"
    ((count++))
done
