#!/usr/bin/env bash
# This is a Bash script that displays "Best School" 10 times.
# On the 9th iteration, it displays "Best School" and then "Hi" on a new line.
# Counter variable
count=1
# While loop to display "Best School" 10 times
while [ $count -le 10 ]; do
    if [ $count -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done
